dice-group/gerbil

- start.sh
Data URL redirects. Added argument to the curl command to take care of redirects.
> Fixed start script

- start.sh
Because I got a 404 on http://github.com/AKSW/gerbil/releases/download/v1.2.1/gerbil_data.zip
> Update gerbil_data zip URL

- start.sh
This PR addresses AKSW/gerbil#146
> Using tomcat7 to run server

- LICENSE
> AGPL-3.0 license

- src/main/webapp/WEB-INF/views/experiment.jsp
Fixing the codacy issues in experiment.jsp
> codacy issues fix

- pom.xml
- src/main/properties/datasets.properties
Dbpedia entity V2 datasets added regarding issue #220 
The pull request raised for the same implementation( https://github.com/dice-group/gerbil/pull/298) will be closed since it has some formatting issues on the pom.xml file which could not be resolved in the previous branch
> Dbpedia entity v2

- .gitignore
- Dockerfile
- docker-config/gerbil.properties
- docker-config/log4j.properties
- docker_build.sh
- run-gerbil.sh
- src/main/properties/entity_checking.properties
- src/main/properties/gerbil.properties
- src/main/properties/log4j.properties
Thanks to @PhilippKuntschik, there is a first version of a dockerized GEBRIL. It may has to be adapted, which should be discussed in this PR (as a follow up of #302).
> Dockerized the GERBIL KE

- src/test/java/org/aksw/gerbil/annotator/impl/qa/QanaryWebServiceFmeasureTest.java
Test case for calculating F-measure for Qanary web service added, regarding the issue #285
> Test case for F-Measure added

- .travis.yml
- src/main/java/org/aksw/gerbil/web/config/RootConfig.java
- src/main/properties/annotators.properties
> Adds OpenTapioca to the list of annotators

- .gitignore
- src/main/java/org/aksw/gerbil/dataset/impl/derczysnki/DerczynskiDataset.java
- src/main/properties/datasets.properties
- src/main/resources/spring/database/schema/experiment-schema.sql
- src/main/webapp/WEB-INF/views/overview.jsp
- Renamed Derczynski dataset according to #276 
- Correlation figure now uses the values as they are #310 
- Also fixes a small issue in the `DerczynskiDataset` class, where the last tweet was not parsed
> Renamed Derczynski dataset, fixed correlation figure bug

- src/main/java/org/aksw/gerbil/annotator/decorator/SingleInstanceSecuringAnnotatorDecorator.java
- src/main/java/org/aksw/gerbil/dataset/check/impl/FileBasedCachingEntityCheckerManager.java
- src/main/java/org/aksw/gerbil/http/InterruptingObserver.java
- src/main/java/org/aksw/gerbil/semantic/sameas/impl/cache/FileBasedCachingSameAsRetriever.java
Fixed #350, made sure that all semaphore permits are released.
> Fixed #350 Checked usage of semaphores

- src/main/java/org/aksw/gerbil/database/ExperimentDAOImpl.java
- src/test/java/org/aksw/gerbil/SingleRunTest.java
- src/test/java/org/aksw/gerbil/dataset/check/HttpBasedEntityCheckerTest.java
This enables the class to handle new experiment result names (refs #379).
> Updated the ExperimentDAOImpl class.

- src/main/java/org/aksw/gerbil/dataset/impl/conll/CoNLLTypeRetriever.java
- src/main/java/org/aksw/gerbil/dataset/impl/conll/GenericCoNLLDataset.java
- src/main/java/org/aksw/gerbil/dataset/impl/derczysnki/DerczynskiDataset.java
- src/main/java/org/aksw/gerbil/dataset/impl/ritter/RitterDataset.java
- src/main/java/org/aksw/gerbil/dataset/impl/wnut/WNUTDataset.java
- src/main/properties/datasets.properties
- src/test/java/org/aksw/gerbil/database/SimpleLoggingDAO4Debugging.java
- src/test/java/org/aksw/gerbil/dataset/impl/derczynski/DerczynskiDatasetTest.java
- src/test/java/org/aksw/gerbil/dataset/impl/ritter/RitterDatasetTest.java
- src/test/java/org/aksw/gerbil/dataset/impl/umbc/UMBCDatasetTest.java
Closes #201
Closes #213 (duplicate)
- Added dataset: WNUT 17 Emerging Entities task
- Added class for CoNLL dataset parsing
- Updated datasets to use the new class: Derczynski, Ritter, UMBC
- Derczynski: added `musicartist` and `other` types which were not parsed before
- Added unimplemented method to SimpleLoggingDAO4Debugging so the build runs again
> Dataset #201

- src/main/java/org/aksw/gerbil/io/nif/utils/NIFPositionHelper.java
> Improved position correction

- src/main/java/org/aksw/gerbil/annotator/impl/falcon/FALCONAnnotator.java
- src/main/java/org/aksw/gerbil/annotator/impl/rel/RELAnnotator.java
- src/main/properties/annotators.properties
Closes #357: ABACO - D2KB
Closes #346: REL - OKETask1
Closes #326: FALCON - C2KB
> Add Annotators: ABACO, REL, FALCON

- pom.xml
- src/test/java/org/aksw/gerbil/dataset/check/HttpBasedEntityCheckerTest.java
- src/test/java/org/aksw/gerbil/execute/OKE2018Task4Test.java
according to the security report of github.
> Increased versions of several libraries 

- pom.xml
(log4j 2.15 has also a vulnerability) 
So please update to 2.16
> log4j to 2.16 

- src/main/java/org/aksw/gerbil/web/config/DatabaseConfig.java
adding exception message for the case when an incorrect database is being used by Gerbil QA.
> Gerbil-QA: Exception message update

- pom.xml
- start.sh
**Dependency Updates and Code Maintenance**
This pull request includes essential updates:
- Updated javadoc and maven source plugin dependencies.
- Added Tomcat 7 plugin configuration.
- Code cleanup: Removed unnecessary blocks.
- Replaced Tomcat 7 with Codehuas Cargo plugin  configuration.
- Spring version updated to 5.3.2 and 5.3.14.
> Spring Version Upgrade

- .github/workflows/maven.yml
- .gitignore
- src/main/properties/datasets.properties
- src/test/java/org/aksw/gerbil/OKEChallengeNIFTest.java
- start.sh
- Added configuration for kore 50 DataSet
- Modified Gerbil data Path
> Added KORE-50 DYWC dataset

- src/main/java/org/aksw/gerbil/transfer/FileMeta.java
- src/main/java/org/aksw/gerbil/web/FileUploadController.java
- src/main/webapp/WEB-INF/views/config.jsp
Closes : #446 #65 
- Improvised File upload Failure Handling 
- Updated UI
> File Upload Failure Handling
